/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentManagerDialog: typeof import('./src/components/dialogs/AgentManagerDialog.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AutomationDrawer: typeof import('./src/components/automation/AutomationDrawer.vue')['default']
    ChangePasswordDialog: typeof import('./src/components/dialogs/ChangePasswordDialog.vue')['default']
    ChatBubble: typeof import('./src/components/chat/ChatBubble.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    CleanupDialog: typeof import('./src/components/dialogs/CleanupDialog.vue')['default']
    CodeBlockModal: typeof import('./src/components/chat/CodeBlockModal.vue')['default']
    CopyRoundsButton: typeof import('./src/components/chat/CopyRoundsButton.vue')['default']
    DetailModal: typeof import('./src/components/panels/DetailModal.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileChangesBadge: typeof import('./src/components/chat/FileChangesBadge.vue')['default']
    FileChangesDrawer: typeof import('./src/components/chat/FileChangesDrawer.vue')['default']
    HttpTraceBlock: typeof import('./src/components/chat/HttpTraceBlock.vue')['default']
    HttpTracesGroup: typeof import('./src/components/chat/HttpTracesGroup.vue')['default']
    InterruptDialog: typeof import('./src/components/chat/InterruptDialog.vue')['default']
    LeftSidebar: typeof import('./src/components/layout/LeftSidebar.vue')['default']
    MessageToolbar: typeof import('./src/components/chat/MessageToolbar.vue')['default']
    ModelSelector: typeof import('./src/components/panels/ModelSelector.vue')['default']
    PermissionsPanel: typeof import('./src/components/settings/PermissionsPanel.vue')['default']
    RightPanel: typeof import('./src/components/layout/RightPanel.vue')['default']
    RoundFileChangesCard: typeof import('./src/components/chat/RoundFileChangesCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubAgentCard: typeof import('./src/components/chat/SubAgentCard.vue')['default']
    TodoList: typeof import('./src/components/panels/TodoList.vue')['default']
    TodoProgressCard: typeof import('./src/components/chat/TodoProgressCard.vue')['default']
    TokenUsagePanel: typeof import('./src/components/chat/TokenUsagePanel.vue')['default']
    ToolCallCard: typeof import('./src/components/chat/ToolCallCard.vue')['default']
    ToolCardRouter: typeof import('./src/components/chat/tools/ToolCardRouter.vue')['default']
    ToolField: typeof import('./src/components/chat/tools/ToolField.vue')['default']
    ToolFileCard: typeof import('./src/components/chat/tools/ToolFileCard.vue')['default']
    ToolFileEditCard: typeof import('./src/components/chat/tools/ToolFileEditCard.vue')['default']
    ToolFileWriteCard: typeof import('./src/components/chat/tools/ToolFileWriteCard.vue')['default']
    ToolGenericCard: typeof import('./src/components/chat/tools/ToolGenericCard.vue')['default']
    ToolGroupPanel: typeof import('./src/components/panels/ToolGroupPanel.vue')['default']
    ToolTerminalCard: typeof import('./src/components/chat/tools/ToolTerminalCard.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
