/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentEditorDialog: typeof import('./src/components/dialogs/AgentEditorDialog.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    ChatBubble: typeof import('./src/components/chat/ChatBubble.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    CopyRoundsButton: typeof import('./src/components/chat/CopyRoundsButton.vue')['default']
    DetailModal: typeof import('./src/components/panels/DetailModal.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    HttpTraceBlock: typeof import('./src/components/chat/HttpTraceBlock.vue')['default']
    InterruptDialog: typeof import('./src/components/chat/InterruptDialog.vue')['default']
    LeftSidebar: typeof import('./src/components/layout/LeftSidebar.vue')['default']
    MessageToolbar: typeof import('./src/components/chat/MessageToolbar.vue')['default']
    ModelSelector: typeof import('./src/components/panels/ModelSelector.vue')['default']
    RightPanel: typeof import('./src/components/layout/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoList: typeof import('./src/components/panels/TodoList.vue')['default']
    TodoProgressCard: typeof import('./src/components/chat/TodoProgressCard.vue')['default']
    TokenUsagePanel: typeof import('./src/components/chat/TokenUsagePanel.vue')['default']
    ToolCallCard: typeof import('./src/components/chat/ToolCallCard.vue')['default']
    ToolGroupPanel: typeof import('./src/components/panels/ToolGroupPanel.vue')['default']
  }
}
